<a href="https://colab.research.google.com/github/Gopichandkollu/Python-with-ML/blob/main/Day_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [3]:
d=[]
for i in h:
    d.append(i+5)

In [4]:
d

[35, 25, 10, 13, 14]

In [5]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [6]:
tuple (x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [7]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [8]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [9]:
m

[36, 81, 49, 64]

In [10]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [11]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [12]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529, 9604])

In [13]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [14]:
arr[arr>50]

array([70, 80, 54, 98])

In [15]:
arr[arr<20]

array([], dtype=int64)

In [16]:
np.where(arr>50)

(array([3, 4, 7, 9]),)