<a href="https://colab.research.google.com/github/Gopichandkollu/Python-with-ML/blob/main/Day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [4]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [5]:
type(d)

numpy.ndarray

In [6]:

tuple(j)

(5, 7, 2, 8, 4, 7)

In [7]:
d.shape

(6,)

In [8]:
d.ndim

1

In [9]:
d.size

6

In [10]:
h=d.reshape(2,3)
h

array([[5, 7, 2],
       [8, 4, 7]])

In [11]:
h.size

6

In [12]:
h.shape

(2, 3)

In [13]:
h.ndim

2

In [14]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [15]:
type(s)

list

In [16]:
import numpy as np

In [17]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [18]:
arr1.shape

(5, 4)

In [19]:
arr1.size

20

In [20]:
arr1.ndim

2

In [21]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [22]:
k.size

20

In [23]:
k.ndim

3

In [24]:
k.shape

(2, 2, 5)

In [25]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [26]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [27]:
y.ndim

1

In [28]:
z=arr1.reshape(1,20)
z

array([[ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55,
        90, 40, 70, 60]])

In [29]:
z.ndim

2

In [30]:
arr1.shape

(5, 4)

In [31]:
arr1.reshape(2,2,5,1)

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [32]:
range(5,20)

range(5, 20)

In [33]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [34]:
range(3,101)

range(3, 101)

In [35]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [36]:
tuple(range(3,13,2))

(3, 5, 7, 9, 11)

In [37]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [38]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [39]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [40]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [41]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [42]:
range(len(j))

range(0, 11)

In [43]:
for i in range(len(j)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [44]:
j[0:11:2]

[5, 23, 62, 80, 77, 80]

In [45]:

j[1:11:2]

[87, 46, 84, 45, 33]

In [46]:

y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [47]:
y

[87, 46, 84, 45, 33]

In [48]:
x

[5, 23, 62, 80, 77, 80]

In [49]:
for i in j:
    print(i)

5
87
23
46
62
84
80
45
77
33
80


In [50]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [51]:
np.mean(d)

40.0

In [52]:
np.median(d)

40.0

In [53]:
np.var(d)

400.0

In [54]:
np.std(d)

20.0

In [55]:
np.max(d)

70

In [56]:
np.min(d)

10

In [57]:
q1=np.quantile(d,0.25)
q1

30.0

In [58]:
q2=np.quantile(d,0.5)
q2

40.0

In [59]:
q3=np.quantile(d,0.75)
q3

50.0

In [60]:
r=np.random.rand(10,5)
r

array([[0.26520656, 0.63035029, 0.8911086 , 0.20580184, 0.7745352 ],
       [0.9651218 , 0.37535864, 0.35593239, 0.96042216, 0.0790401 ],
       [0.89033966, 0.35014129, 0.29941033, 0.03872423, 0.11079559],
       [0.28212126, 0.3800918 , 0.08615779, 0.18948385, 0.00356752],
       [0.10909579, 0.84889699, 0.10209587, 0.66171382, 0.31219566],
       [0.25216256, 0.77214506, 0.82954419, 0.61822505, 0.06046029],
       [0.90998914, 0.98717916, 0.70313949, 0.45730491, 0.50150839],
       [0.02947061, 0.78490964, 0.30330089, 0.43802835, 0.16281866],
       [0.20012193, 0.40184991, 0.97020527, 0.68165755, 0.54771014],
       [0.14326908, 0.87524198, 0.82193971, 0.29798562, 0.17355536]])

In [61]:
r.size

50

In [62]:
r.ndim

2

In [63]:
s=np.random.rand(5,3,2) # 0 to 1
s

array([[[0.15287071, 0.62226526],
        [0.77047122, 0.87411145],
        [0.9689305 , 0.23017124]],

       [[0.69757322, 0.24472553],
        [0.96937817, 0.12478123],
        [0.68937117, 0.16778317]],

       [[0.6581102 , 0.66729144],
        [0.90067396, 0.18112215],
        [0.94837443, 0.58695857]],

       [[0.94816123, 0.39764039],
        [0.07281354, 0.82534463],
        [0.79439199, 0.94829896]],

       [[0.86680149, 0.45217204],
        [0.98990808, 0.39884139],
        [0.18623385, 0.2361786 ]]])

In [64]:
t=np.random.rand(1)
t

array([0.4751331])

In [65]:
s.ndim

3

In [66]:
t.ndim

1

In [67]:
np.random.randn(30,1)

array([[ 0.05956531],
       [-0.09900163],
       [ 0.17719608],
       [-1.11101815],
       [-0.07315681],
       [ 0.3421796 ],
       [-1.51824834],
       [ 0.95096477],
       [ 0.9631174 ],
       [ 0.9894624 ],
       [-0.9201616 ],
       [-0.00431751],
       [-1.23192844],
       [-0.73684639],
       [ 0.62373177],
       [-0.2491711 ],
       [ 0.63358904],
       [-0.1669061 ],
       [-0.46770139],
       [ 0.9481888 ],
       [-0.8396031 ],
       [-0.40893294],
       [ 1.21179484],
       [-1.17080932],
       [ 0.74220101],
       [ 0.45824441],
       [-0.74853623],
       [ 0.12161059],
       [-2.6054169 ],
       [ 0.38544855]])

In [68]:
np.random.normal(10,2,(4,5))

array([[ 8.57309618,  9.75253198,  7.39607785, 10.59389543,  7.85850572],
       [11.4480272 ,  8.37740487,  8.09921196, 13.32765099,  9.74549632],
       [10.0936838 ,  7.4541888 , 15.21995354,  9.4656753 ,  9.15431322],
       [ 8.23903453,  7.32768892,  7.83613201, 10.55961649, 12.00690825]])

In [69]:
np.random.randint(35,86,(5,5))

array([[81, 44, 41, 79, 63],
       [47, 77, 46, 68, 43],
       [83, 40, 66, 46, 53],
       [80, 44, 84, 68, 40],
       [42, 69, 57, 61, 75]])