<a href="https://colab.research.google.com/github/Gopichandkollu/Python-with-ML/blob/main/Day_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:







a = np.random.randint(30,99,(7,8))
a

array([[80, 51, 55, 49, 37, 84, 61, 82],
       [82, 86, 64, 80, 77, 88, 88, 34],
       [79, 67, 97, 94, 80, 76, 69, 85],
       [80, 75, 65, 82, 79, 96, 81, 79],
       [30, 80, 73, 90, 89, 93, 61, 96],
       [54, 77, 30, 53, 79, 41, 37, 80],
       [89, 48, 95, 57, 51, 41, 35, 88]])

In [3]:
np.random.seed(55)
a = np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [4]:
a[-1]

79

In [5]:
a[4]

85

In [6]:
a.ndim

1

In [7]:
a[19]

79

In [8]:
b=np.random.randint(20,80,(8,9))
b

array([[44, 68, 34, 76, 30, 79, 79, 48, 61],
       [64, 44, 72, 49, 64, 41, 33, 72, 61],
       [78, 53, 65, 44, 38, 36, 65, 75, 47],
       [38, 76, 62, 52, 73, 30, 74, 23, 44],
       [78, 27, 38, 21, 39, 65, 73, 50, 39],
       [30, 45, 22, 44, 52, 33, 55, 31, 54],
       [35, 53, 62, 54, 68, 79, 41, 40, 23],
       [27, 40, 33, 54, 36, 60, 39, 46, 34]])

In [9]:
b.shape

(8, 9)

In [10]:
b.ndim

2

In [11]:
b[0]

array([44, 68, 34, 76, 30, 79, 79, 48, 61])

In [12]:
b[7,0]

27

In [13]:
b[2:6:1,1:7:2]

array([[53, 44, 36],
       [76, 52, 30],
       [27, 21, 65],
       [45, 44, 33]])

In [14]:
import pandas as pd

In [15]:
k=[4,7,2,9,7,3,90,50]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [16]:
np.array(k)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [17]:
pd.Series(k)

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [18]:
pd.DataFrame(k)

0
0   4
1   7
2   2
3   9
4   7
5   3
6  90
7  50

In [19]:
q=[[4,7],[2,9],[7,3],[90,50]]
q

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [20]:
t=np.array(q)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [21]:
t.ndim

2

In [22]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [23]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [24]:
df=pd.DataFrame(t,columns=['name','sub'],index=[1,2,3,4])
df

name  sub
1     4    7
2     2    9
3     7    3
4    90   50

In [25]:
df.columns

Index(['name', 'sub'], dtype='object')

In [26]:
df['name']

1     4
2     2
3     7
4    90
Name: name, dtype: int64

In [27]:
df['name'].mean()

25.75

In [28]:
df['name'].mode()

0     2
1     4
2     7
3    90
Name: name, dtype: int64

In [29]:
df['name'].median()

5.5

In [30]:
df['name'].std()

42.88259165053655

In [31]:
df['name'].min()

2

In [32]:
df['name'].max()

90

In [33]:
df['name'].quantile(0.25)

3.5

In [34]:
df.sub

<bound method DataFrame.sub of    name  sub
1     4    7
2     2    9
3     7    3
4    90   50>